module.exports = {
  apps: [
    {
      name: 'app',
      script: './http.js',
      env_development: {
        NODE_ENV: 'development',
        PORT: '2828',
        MONGO_URL: 'mongodb://localhost:27017/king-Rummy',
        EXPIRED_TIME: '7d',
        REDIS_HOST: '127.0.0.1',
        SECRET_KEY: 'shukrana_mushkurana',
        HOST_URL: 'http://localhost:3000',
        TWILIO_ACCOUNT_SID: 'AC0dd22ae15db805442cdd523564daa44d',
        TWILIO_AUTH_TOKEN: '8ad38cab84ff11285efbcef3fde1c95a',
        TWILIO_NUMBER: '+12058578375',
        MAIL_SERVICE: 'justmintu7@gmail.com',
        MAIL_ID: 'justmintu7@gmail.com',
        PASSWORD: 'password123#',
        COUNTRY_CODE: '+91',
        LOG_LEVEL: 'debug',
      },
      env_production: {
        NODE_ENV: 'production',
        PORT: '3000',
        MONGO_URL: 'mongodb+srv://appsomania:appsomania@cluster0.1tmcu.mongodb.net/myFirstDatabase?retryWrites=true&w=majority',
        EXPIRED_TIME: '1d',
        REDIS_HOST: '127.0.0.1',
        SECRET_KEY: 'shukrana_mushkurana',
        HOST_URL: 'http://localhost:3000',
        TWILIO_ACCOUNT_SID: 'AC0dd22ae15db805442cdd523564daa44d',
        TWILIO_AUTH_TOKEN: '8ad38cab84ff11285efbcef3fde1c95a',
        TWILIO_NUMBER: '+12058578375',
        MAIL_SERVICE: 'justmintu7@gmail.com',
        MAIL_ID: 'justmintu7@gmail.com',
        PASSWORD: 'password123#',
        COUNTRY_CODE: '+91',
        LOG_LEVEL: 'debug',
      },
    },
  ],
};
